import os
import numpy as np
RESULTS_PATH = "F:\\users\\prasetia\\data\\Children\\children_sync\\results\\"
BAYESIAN_RESULTS_PATH = os.path.join(RESULTS_PATH, "bayesian_ttest")


# decision tree
BAYESIAN_RESULTS_MODEL_PATH = os.path.join(BAYESIAN_RESULTS_PATH, "model")
BAYESIAN_RESULTS_MODEL_PRE_PATH = os.path.join(BAYESIAN_RESULTS_PATH, "model", "pre")
BAYESIAN_RESULTS_MODEL_AFTER_PATH = os.path.join(BAYESIAN_RESULTS_PATH, "model", "after")
BAYESIAN_RESULTS_MODEL_POST_PATH = os.path.join(BAYESIAN_RESULTS_PATH, "model", "post")
BAYESIAN_RESULTS_POSTERIOR_PATH = os.path.join(BAYESIAN_RESULTS_PATH, "posterior")
BAYESIAN_RESULTS_PDP_PRE_PATH = os.path.join(BAYESIAN_RESULTS_PATH, "PDP", "PRE")
BAYESIAN_RESULTS_PDP_AFTER_PATH = os.path.join(BAYESIAN_RESULTS_PATH, "PDP", "AFTER")
BAYESIAN_RESULTS_PDP_POST_PATH = os.path.join(BAYESIAN_RESULTS_PATH, "PDP", "POST")
BAYESIAN_RESULTS_PPC_PATH = os.path.join(BAYESIAN_RESULTS_PATH, "PPC")
BAYESIAN_RESULTS_VI_PATH = os.path.join(BAYESIAN_RESULTS_PATH, "VI")
BAYESIAN_RESULTS_CONVERGENCE_PATH = os.path.join(BAYESIAN_RESULTS_PATH, "convergence")
BAYESIAN_RESULTS_COMPARISON_PATH = os.path.join(BAYESIAN_RESULTS_PATH, "model_comparison")
BAYESIAN_RESULTS_MEAN_DIFF_PATH = os.path.join(BAYESIAN_RESULTS_PATH, "mean_difference")

STATISTICAL_RESULTS_PATH = os.path.join(BAYESIAN_RESULTS_PATH, "statistical")
# NUTS varible
N_SAMPLES = 5000
N_TUNE = 3000
N_CHAINS = 4
N_CORE = 4
TARGET_ACC = 0.99
SAMPLES_VI = 200

XS_VALUES = [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 0.99]
# XS_VALUES = [0.1, 0.15, 0.25, 0.35, 0.45, 0.55, 0.65, 0.75, 0.85, 0.95]

